config/routes.rb
Rails.application.routes.draw do
  resources :searchrepos, only: [:index]

  # set index as root homepage
  root 'searchrepos#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/searchrepo.rb
class Searchrepo < ApplicationRecord
    include HTTParty    
    @@url = "https://api.github.com/search/repositories"


    # Query repo 
    def find(name)
       @results = HTTParty.get(@@url, query: { q: name }).parsed_response
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searchrepos_controller.rb
class SearchreposController < ApplicationController
  before_action :set_searchrepo, only: [:show, :edit, :update, :destroy]

  # GET /searchrepos
  # GET /searchrepos.json
  def index
    if params[:search]
      # call model to get api using search parameters
      @searchrepo = Searchrepo.new.find(params[:search])
      respond_to do |format|
        # partial formatting of webpage
        format.js { render partial: 'search-results'}
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searchrepos_helper.rb
module SearchreposHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Search</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/searchrepos/_form.html.erb
<%= form_with(model: searchrepo, local: true) do |form| %>
  <% if searchrepo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(searchrepo.errors.count, "error") %> prohibited this searchrepo from being saved:</h2>

      <ul>
        <% searchrepo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/searchrepos/_results.html.erb
<%# Partial update of results in table %>
<table id="tbl" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%;">
    <caption>All matching respository</caption>
    <thead>
    <tr>
    <th>Repository</th>
    <th>Description</th>
    <th>Date Updated</th>
    </tr>
    </thead>
    <tbody>
        <% @searchrepo['items'].each do |repo| %>
            <tr>
            <td><%= repo['full_name'] %></td>
            <td><%= repo['description'] %></td>
            <td><%= repo['updated_at'] %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/searchrepos/_search-results.js.erb
$("#search-results").html("<%= escape_javascript(render :partial => 'results') %>");

app/views/searchrepos/edit.html.erb
<h1>Editing Searchrepo</h1>

<%= render 'form', searchrepo: @searchrepo %>

<%= link_to 'Show', @searchrepo %> |
<%= link_to 'Back', searchrepos_path %>

app/views/searchrepos/index.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/awesomplete/1.1.5/awesomplete.base.css"/>


<section class="head">
    <div class="container">
        <h2 class="text-center"><span>GitHub Search</span></h2>
    </div>
</section>
<br>
<hr>
<br>
<%= form_tag(searchrepos_path, method: "get", :remote => true) do %>
  <%= text_field_tag :search, params[:search], id: "autocomplete", placeholder: "Enter search term" %>
  <%= submit_tag "Search" %>
<% end %>
<br>
<hr>
<br>
<div id="search-results" class="pt-4">
  <table id="tbl" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%;">
    <caption>All matching respository</caption>
        <thead>
        <tr>
          <th>Repository</th>
          <th>Description</th>
          <th>Date Updated</th>
        </tr>
        </thead>
        <tbody>
        <% if params[:search] %>
            <% @searchrepo['items'].each do |repo| %>
                <tr>
                <td><%= repo['full_name'] %></td>
                <td><%= repo['description'] %></td>
                <td><%= repo['updated_at'] %></td>
                </tr>
            <% end %>
        <% end %>
        </tbody>
      </table>

</div>



<script src="https://cdnjs.cloudflare.com/ajax/libs/awesomplete/1.1.5/awesomplete.js" async></script>
<%# Ajax for autocomplete %>
<script>
var ajax = new XMLHttpRequest();
ajax.open("GET", "https://raw.githubusercontent.com/bevacqua/correcthorse/master/wordlist.json", true);
ajax.onload = function() {
	var list = JSON.parse(ajax.responseText);
	new Awesomplete(document.querySelector("#autocomplete"),{ list: list });
};
ajax.send();
</script>

app/views/searchrepos/new.html.erb
<h1>New Searchrepo</h1>

<%= render 'form', searchrepo: @searchrepo %>

<%= link_to 'Back', searchrepos_path %>

app/views/searchrepos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @searchrepo.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @searchrepo.body %>
</p>

<p>
  <strong>Date:</strong>
  <%= @searchrepo.date %>
</p>

<%= link_to 'Edit', edit_searchrepo_path(@searchrepo) %> |
<%= link_to 'Back', searchrepos_path %>